version: '3.3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~${USERID}/plex/config:/config   #in case of migrating a plexmediaserver, for example, from the default installation of Ubuntu, put the folder in this directory "Library" from \var\lib\plexmediaserver\
      - ~${USERID}/plex/transcode:/transcode   #the best solution would be to mount the directory on a fast drive
      - ${GENERAL_SHARE_PATH}:${GENERAL_SHARE_PATH}   #This forwarding is my main directory with media files, in my case I store all media libraries in it, but this is not necessary and can be configured
    environment:
      - TZ=${TZ}